#!/usr/bin/env bash
#
# Unlock YTPlus paywall by binary-patching `_dvnLocked` in YTLite.dylib so it
# always returns 0 (= "not locked"). All feature gates that consult this symbol
# therefore see an unlocked state. The Patreon login flow itself is left intact
# but is never reached because no gate is triggered.
#
# Usage:
#   Scripts/patch_paywall.sh <input.deb> [output.deb]
#
# Requires: tar, xz, nm, ldid (or codesign), and Python 3.
# Python handles both the ar unpack/repack and the byte patch so this script
# stays portable between macOS (BSD ar) and CI runners.

set -euo pipefail

IN_DEB="${1:?usage: patch_paywall.sh <input.deb> [output.deb]}"
OUT_DEB="${2:-$IN_DEB}"

if [[ ! -f "$IN_DEB" ]]; then
  echo "::error::input deb not found: $IN_DEB" >&2
  exit 2
fi

WORK="$(mktemp -d -t ytp_paywall.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT

echo "[patch_paywall] extracting $IN_DEB -> $WORK"
mkdir -p "$WORK/deb" "$WORK/data" "$WORK/control"
python3 - "$IN_DEB" "$WORK/deb" <<'PY'
import os, sys
src, dst = sys.argv[1], sys.argv[2]
with open(src, 'rb') as fp:
    blob = fp.read()
assert blob[:8] == b'!<arch>\n', f'not an ar archive: {src}'
off = 8
while off < len(blob):
    hdr = blob[off:off+60]
    if len(hdr) < 60: break
    name = hdr[0:16].rstrip(b' /\x00').decode()
    size = int(hdr[48:58].decode().strip())
    data = blob[off+60:off+60+size]
    with open(os.path.join(dst, name), 'wb') as out:
        out.write(data)
    off += 60 + size
    if off % 2: off += 1  # ar pads to even byte
PY

# data archive may be .lzma or .xz depending on tooling
if   [[ -f "$WORK/deb/data.tar.lzma" ]]; then DATA_ARCHIVE="data.tar.lzma"
elif [[ -f "$WORK/deb/data.tar.xz"   ]]; then DATA_ARCHIVE="data.tar.xz"
elif [[ -f "$WORK/deb/data.tar.gz"   ]]; then DATA_ARCHIVE="data.tar.gz"
else
  echo "::error::unsupported data archive in $IN_DEB" >&2
  ls "$WORK/deb" >&2
  exit 3
fi

case "$DATA_ARCHIVE" in
  *.lzma) xz --decompress --keep --stdout "$WORK/deb/$DATA_ARCHIVE" | tar -C "$WORK/data" -xf - ;;
  *.xz)   xz --decompress --keep --stdout "$WORK/deb/$DATA_ARCHIVE" | tar -C "$WORK/data" -xf - ;;
  *.gz)   tar -C "$WORK/data" -xzf "$WORK/deb/$DATA_ARCHIVE" ;;
esac

DYLIB="$(find "$WORK/data" -type f -name 'YTLite.dylib' | head -n1)"
if [[ -z "$DYLIB" || ! -f "$DYLIB" ]]; then
  echo "::error::YTLite.dylib not found inside .deb" >&2
  find "$WORK/data" -maxdepth 6 >&2
  exit 4
fi
echo "[patch_paywall] target: $DYLIB"

python3 - "$DYLIB" <<'PY'
import struct, subprocess, sys
path = sys.argv[1]

nm = subprocess.check_output(['nm', '-g', path]).decode()
addr = None
for line in nm.splitlines():
    parts = line.split()
    if len(parts) >= 3 and parts[-1] == '_dvnLocked' and parts[-2] == 'T':
        addr = int(parts[0], 16)
        break
if addr is None:
    sys.exit('::error::symbol _dvnLocked not found in dylib — upstream changed layout')

with open(path, 'rb') as fp:
    data = fp.read()

# Sanity-check original five-instruction body of _dvnLocked:
#   adrp  x8, <page>          (variable encoding, low 5 bits of byte 3 are mask)
#   ldrb  w8, [x8, #imm]      (39513d08 for imm=0x4f1; high bits of imm vary)
#   mov   w9, #0x1            52800029
#   bic   w0, w9, w8          0a280120
#   ret                       d65f03c0
expected_tail = bytes.fromhex('29008052' '2001280a' 'c0035fd6')
actual_tail   = data[addr+8:addr+20]
if actual_tail != expected_tail:
    sys.exit(f'::error::_dvnLocked layout mismatch at {hex(addr)}: tail={actual_tail.hex()} (refusing to patch)')

# Patch: mov w0, #0 ; ret ; nop ; nop ; nop
patch = struct.pack('<IIIII',
    0x52800000,  # mov w0, #0
    0xd65f03c0,  # ret
    0xd503201f,  # nop
    0xd503201f,
    0xd503201f,
)
with open(path, 'r+b') as fp:
    fp.seek(addr)
    fp.write(patch)
print(f'[patch_paywall] patched _dvnLocked at 0x{addr:x} ({len(patch)} bytes)')
PY

# Re-sign so the Mach-O code signature matches the new bytes. Prefer ldid (the
# CI installs it via brew); fall back to codesign for local runs on macOS.
if command -v ldid >/dev/null 2>&1; then
  ldid -S "$DYLIB"
  echo "[patch_paywall] re-signed with ldid"
elif command -v codesign >/dev/null 2>&1; then
  codesign --remove-signature "$DYLIB" 2>/dev/null || true
  codesign -s - "$DYLIB"
  echo "[patch_paywall] re-signed with codesign (ad-hoc)"
else
  echo "::warning::neither ldid nor codesign found — dylib not re-signed" >&2
fi

# Strip Patreon-section copy from the bundled binary-plist localizations so the
# UI no longer shows "active Patreon subscription required" messaging. The
# section *header* itself is generated by an obfuscated method we don't touch;
# leaving the keys present but blank keeps layout sane without paywall text.
PATREON_KEYS=(
  "FeaturesNotActivated"
  "Log-inViaPatreon"
  "AccessDenied"
  "ManageAccount"
  "LogOut"
  "LogOutTitle"
  "LogOutMessage"
  "SkipLogInAlert"
)

if command -v plutil >/dev/null 2>&1; then
  while IFS= read -r -d '' STR; do
    for KEY in "${PATREON_KEYS[@]}"; do
      plutil -replace "$KEY" -string " " "$STR" 2>/dev/null || true
    done
  done < <(find "$WORK/data" -type f -name 'Localizable.strings' -print0)
  echo "[patch_paywall] sanitized Patreon copy in bundled localizations"
fi

# Repack data.tar.{lzma,xz,gz} preserving original compression scheme.
echo "[patch_paywall] repacking $DATA_ARCHIVE"
(
  cd "$WORK/data"
  case "$DATA_ARCHIVE" in
    *.lzma) tar --format=gnutar -cf - . | xz -z --format=lzma -c > "$WORK/deb/$DATA_ARCHIVE" ;;
    *.xz)   tar --format=gnutar -cf - . | xz -z -c        > "$WORK/deb/$DATA_ARCHIVE" ;;
    *.gz)   tar --format=gnutar -czf "$WORK/deb/$DATA_ARCHIVE" . ;;
  esac
)

# Repack .deb (ar archive in dpkg member order: debian-binary, control, data).
OUT_ABS="$(cd "$(dirname "$OUT_DEB")" && pwd)/$(basename "$OUT_DEB")"
python3 - "$WORK/deb" "$OUT_ABS" "$DATA_ARCHIVE" <<'PY'
import os, sys
src_dir, out, data_name = sys.argv[1], sys.argv[2], sys.argv[3]
members = ['debian-binary', 'control.tar.gz', data_name]
with open(out, 'wb') as fp:
    fp.write(b'!<arch>\n')
    for name in members:
        path = os.path.join(src_dir, name)
        with open(path, 'rb') as src:
            payload = src.read()
        # ar header: name(16) mtime(12) uid(6) gid(6) mode(8) size(10) magic(2)
        hdr = f'{name:<16}{0:<12}{0:<6}{0:<6}{"100644":<8}{len(payload):<10}'.encode() + b'`\n'
        assert len(hdr) == 60
        fp.write(hdr)
        fp.write(payload)
        if len(payload) % 2:
            fp.write(b'\n')
PY
echo "[patch_paywall] wrote $OUT_ABS"
